---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ovsa85241095/public_html/panel5/ 
    - /bin/cp -r examp/file1 $DEPLOYPATH    
    - /bin/cp -r nemonehe $DEPLOYPATH    
    - /bin/cp * $DEPLOYPATH    